### ISSUE TITLE
org.apache.axiom.soap.SOAPProcessingException: First Element must contain the local name, Envelope , but found definitions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ajayz15/magja#68]
```
Cannot connect to Magento
java.lang.RuntimeException: Cannot connect to Magento
    at com.google.code.magja.soap.MagentoSoapClient.<init>(MagentoSoapClient.java:137)
    at com.google.code.magja.soap.MagentoSoapClient.<init>(MagentoSoapClient.java:147)
    at com.google.code.magja.soap.MagentoSoapClient.getInstance(MagentoSoapClient.java:113)
    at RulTemporizadorECommerce.execute(RulTemporizadorECommerce.java:55)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:207)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:560)
Caused by: org.apache.axis2.AxisFault: First Element must contain the local 
name, Envelope , but found definitions
    at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
    at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:123)
    at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:67)
    at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:354)
    at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
    at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
    at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
    at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:555)
    at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:531)
    at com.google.code.magja.soap.MagentoSoapClient.login(MagentoSoapClient.java:290)
    at com.google.code.magja.soap.MagentoSoapClient.<init>(MagentoSoapClient.java:134)
    ... 5 more
Caused by: org.apache.axiom.soap.SOAPProcessingException: First Element must 
contain the local name, Envelope , but found definitions
    at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.constructNode(StAXSOAPModelBuilder.java:299)
    at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.createOMElement(StAXSOAPModelBuilder.java:246)
    at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.createNextOMElement(StAXSOAPModelBuilder.java:228)
    at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:249)
    at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.getSOAPEnvelope(StAXSOAPModelBuilder.java:198)
    at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.<init>(StAXSOAPModelBuilder.java:154)
    at org.apache.axiom.om.impl.llom.factory.AbstractOMMetaFactory.internalCreateStAXSOAPModelBuilder(AbstractOMMetaFactory.java:119)
    at org.apache.axiom.om.impl.llom.factory.AbstractOMMetaFactory.createSOAPModelBuilder(AbstractOMMetaFactory.java:129)
    at org.apache.axiom.om.OMXMLBuilderFactory.createSOAPModelBuilder(OMXMLBuilderFactory.java:426)
    at org.apache.axiom.om.OMXMLBuilderFactory.createSOAPModelBuilder(OMXMLBuilderFactory.java:405)
    at org.apache.axis2.builder.SOAPBuilder.processDocument(SOAPBuilder.java:55)
    at org.apache.axis2.transport.TransportUtils.createDocumentElement(TransportUtils.java:179)
    at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:145)
    at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:108)
    ... 14 more

```

Original issue reported on code.google.com by `bentor...@gmail.com` on 27 Feb 2015 at 7:17

**Comment by voxoid0** [comment]
Having the same issue.
